services:
  - type: web
    name: ecg-scan-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && flask --app run.py db upgrade
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 run:app
    healthCheckPath: /api/getmap